del /f /q *.~*
del /f /q *.obj
del /f /q *.tds
del /f /q *.exe
del /f /q crc\*.~*
del /f /q crc\*.obj
del /f /q crc\*.tds
del /f /q crc\*.exe
del /f /q CommPort\*.~*
del /f /q CommPort\*.obj
del /f /q CommPort\*.tds
del /f /q CommPort\*.exe
